services:
  - type: web
    name: BROOM
    env: python
    region: frankfurt # or your preferred region
    buildCommand: |
      git submodule update --init --recursive;
      cd IOT-PM-Suite-Backend;
      pip install -r requirements.txt;
      cd ../IOT-PM-Suite;
      npm install;
      npm run build --prod;
    startCommand: gunicorn app:app
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0 # Adjust accordingly
