services:
  - type: web
    name: BROOM
    env: python
    region: frankfurt
    buildCommand: |
      git submodule update --init;           
      git submodule foreach git fetch;      
      git submodule foreach git checkout main;
      git submodule foreach git pull;
      cd IOT-PM-Suite-Backend;
      pip install -r requirements.txt;
      cd ../IOT-PM-Suite;
      npm install;
      npm run build --prod;
    startCommand: gunicorn app:app
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
